version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    container_name: my-sql-server-container
    environment:
      SA_PASSWORD: "SqlServerDocker2023*"  # Cambia esto por una contraseña segura
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge